spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate

audigo:
  cors:
    allowed-origins: ${AUDIGO_CORS_ALLOWED_ORIGINS}

  auth:
    jwt-secret: ${AUDIGO_JWT_SECRET}

  oauth:
    kakao:
      client-id: ${KAKAO_REST_API_KEY}
      client-secret: ${KAKAO_CLIENT_SECRET}
      redirect-uri: ${KAKAO_REDIRECT_URI}
